In [2]:
import pandas as pd
import numpy as np
from datetime import datetime
import warnings
import matplotlib.pyplot as plt
%matplotlib inline

warnings.filterwarnings('ignore')

In [5]:
data1 = pd.read_csv("C:\\Users\\rohan.fouzdar\\Downloads\\all_matches.csv")
data1.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print(data1.columns)

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [7]:
d2015=data1[data1.start_date>="2015-01-01"]

In [8]:
d2015['runs_on_ball']=d2015['runs_off_bat']+d2015['extras']
d2015.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,runs_on_ball
108850,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.1,Kings XI Punjab,Kolkata Knight Riders,M Vijay,V Sehwag,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
108851,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.2,Kings XI Punjab,Kolkata Knight Riders,M Vijay,V Sehwag,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
108852,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.3,Kings XI Punjab,Kolkata Knight Riders,M Vijay,V Sehwag,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
108853,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.4,Kings XI Punjab,Kolkata Knight Riders,M Vijay,V Sehwag,...,NaN,NaN,NaN,NaN,NaN,caught,M Vijay,NaN,NaN,0
108854,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.5,Kings XI Punjab,Kolkata Knight Riders,WP Saha,V Sehwag,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [9]:
d2015['Over']=d2015['ball'].apply(np.ceil)

In [10]:
d2015['venue'].value_counts()

Wankhede Stadium                                        8825
Eden Gardens                                            8669
Dubai International Cricket Stadium                     6380
Sheikh Zayed Stadium                                    5301
Maharashtra Cricket Association Stadium                 5055
M Chinnaswamy Stadium                                   5012
Feroz Shah Kotla                                        4488
Rajiv Gandhi International Stadium, Uppal               4381
Rajiv Gandhi International Stadium                      3609
M.Chinnaswamy Stadium                                   3494
Arun Jaitley Stadium                                    3356
Sawai Mansingh Stadium                                  3286
Sharjah Cricket Stadium                                 2878
Punjab Cricket Association IS Bindra Stadium, Mohali    2574
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     2561
Punjab Cricket Association IS Bindra Stadium            2429
Saurashtra Cricket Association Stadium                  2381
MA Chidambaram Stadium                                  2130
MA Chidambaram Stadium, Chepauk                         1728
Holkar Cricket Stadium                                  1557
Sardar Patel Stadium, Motera                             952
Shaheed Veer Narayan Singh International Stadium         947
Green Park                                               921
Punjab Cricket Association Stadium, Mohali               845
Brabourne Stadium                                        761
MA Chidambaram Stadium, Chepauk, Chennai                 498
JSCA International Stadium Complex                       247
Wankhede Stadium, Mumbai                                 239
Name: venue, dtype: int64

In [11]:
d2015['overkey']=d2015['match_id'].astype(str)+d2015['season'].astype(str)+d2015['Over'].astype(str)+d2015['innings'].astype(str)
doverruns=d2015[d2015.innings>0].groupby('overkey')['runs_on_ball'].sum().to_frame().reset_index()

doverruns.head()

            overkey  runs_on_ball
0   108259120171.01             7
1   108259120171.02            11
2  1082591201710.01             4
3  1082591201710.02            13
4  1082591201711.01            10

In [12]:
doverruns.rename(columns= {'runs_on_ball': 'runs_in_over'})

                overkey  runs_in_over
0       108259120171.01             7
1       108259120171.02            11
2      1082591201710.01             4
3      1082591201710.02            13
4      1082591201711.01            10
...                 ...           ...
13859    98101920167.02            10
13860    98101920168.01            10
13861    98101920168.02            10
13862    98101920169.01            13
13863    98101920169.02            21

[13864 rows x 2 columns]

In [13]:
d2015=d2015.merge(doverruns,on='overkey')

In [14]:
d2015.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,runs_on_ball_x,Over,overkey,runs_on_ball_y
0,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.1,Kings XI Punjab,Kolkata Knight Riders,M Vijay,V Sehwag,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,82973320151.01,2
1,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.2,Kings XI Punjab,Kolkata Knight Riders,M Vijay,V Sehwag,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,82973320151.01,2
2,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.3,Kings XI Punjab,Kolkata Knight Riders,M Vijay,V Sehwag,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,82973320151.01,2
3,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.4,Kings XI Punjab,Kolkata Knight Riders,M Vijay,V Sehwag,...,NaN,NaN,caught,M Vijay,NaN,NaN,0,1.0,82973320151.01,2
4,829733,2015,2015-04-18,Maharashtra Cricket Association Stadium,1,0.5,Kings XI Punjab,Kolkata Knight Riders,WP Saha,V Sehwag,...,NaN,NaN,NaN,NaN,NaN,NaN,0,1.0,82973320151.01,2

In [15]:
d2015.rename(columns={'runs_on_ball_x': 'runs_on_ball', 'runs_on_ball_y': 'runs_in_over'}, inplace=True)

In [16]:
d2015['venue'].unique()

array(['Maharashtra Cricket Association Stadium',
       'Sardar Patel Stadium, Motera', 'M Chinnaswamy Stadium',
       'Feroz Shah Kotla',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Eden Gardens', 'MA Chidambaram Stadium, Chepauk',
       'Wankhede Stadium', 'Punjab Cricket Association Stadium, Mohali',
       'Rajiv Gandhi International Stadium, Uppal', 'Brabourne Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium', 'Holkar Cricket Stadium',
       'MA Chidambaram Stadium', 'Sawai Mansingh Stadium',
       'Arun Jaitley Stadium', 'Rajiv Gandhi International Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Sheikh Zayed Stadium', 'Dubai International Cricket Stadium',
       'Sharjah Cricket Stadium',
       'MA Chidambaram Stadium, Chepauk, Chennai',
       'Wankhede Stadium, Mumbai'], dtype=object)

In [17]:
d2015['venue']=d2015['venue'].replace(['M.Chinnaswamy Stadium'],'M Chinnaswamy Stadium')
d2015['venue']=d2015['venue'].replace(['Feroz Shah Kotla'],'Arun Jaitley Stadium')
d2015['venue']=d2015['venue'].replace(['MA Chidambaram Stadium, Chepauk','MA Chidambaram Stadium, Chepauk, Chennai'],'MA Chidambaram Stadium')
d2015['venue']=d2015['venue'].replace(['Wankhede Stadium, Mumbai'],'Wankhede Stadium')
d2015['venue']=d2015['venue'].replace(['Rajiv Gandhi International Stadium, Uppal'],'Rajiv Gandhi International Stadium')
d2015['venue']=d2015['venue'].replace(['Punjab Cricket Association IS Bindra Stadium','Punjab Cricket Association IS Bindra Stadium, Mohali'],'Punjab Cricket Association Stadium, Mohali')

In [21]:
d2015.to_csv('C:\\Users\\rohan.fouzdar\\Downloads\\d2015.csv',sep=',',index=False)